// this file is autogenerated by rest-gen - do not edit
package service

import (
	gin "github.com/gin-gonic/gin"
	"net/http"
)

type RecipeServiceHandler struct {
	handler RecipeServiceInterface
}

func RegisterRecipeServiceRoutes(router *gin.router, handler RecipeServiceHandler) {
	router.GET("/api/v1/recipe/{id}", handler.HandleGetRecipe)
}

func (handler RecipeServiceHandler) HandleGetRecipe(ctx *gin.Context) {
	id := ctx.Param("id")
	GetRecipeResult, err := handler.handler.GetRecipe(id)
	if err != nil {
		ctx.AbortWithError(http.StatusInternalServerError, err)
		return
	}
	ctx.JSON(http.StatusOK, GetRecipeResult)
	return
}
