// this file is autogenerated by rest-gen - do not edit
package service

import "github.com/tgs266/rest-gen/test-gen/com/restgen/recipe/structs"

type RecipeServiceInterface interface {
	// returns a single recipe
	GetRecipe(id string) (structs.Recipe, error)
}
