// this file is autogenerated by rest-gen - do not edit
package structs

import (
	"encoding/json"
	yamlv3 "gopkg.in/yaml.v3"
)

// o.Docs
type Measurement struct {
	Unit  string  `json:"unit" yaml:"unit"`
	Value float32 `json:"value" yaml:"value"`
}

func (measurement Measurement) MarshalJSON() ([]byte, error) {
	return json.Marshal(measurement)
}

func (measurement *Measurement) UnmarshalJSON(bytes []byte) error {
	return json.Unmarshal(bytes, &measurement)
}

func (measurement Measurement) MarshalYAML() ([]byte, error) {
	return yamlv3.Marshal(measurement)
}

func (measurement *Measurement) UnmarshalYAML(bytes []byte) error {
	return yamlv3.Unmarshal(bytes, &measurement)
}

type Recipe struct {
	Id    string `json:"id" yaml:"id"`
	Name  string `json:"name" yaml:"name"`
	Steps []Step `json:"steps" yaml:"steps"`
}

func (recipe Recipe) MarshalJSON() ([]byte, error) {
	if recipe.Steps == nil {
		recipe.Steps = make([]Step, 0)
	}
	return json.Marshal(recipe)
}

func (recipe *Recipe) UnmarshalJSON(bytes []byte) error {
	return json.Unmarshal(bytes, &recipe)
}

func (recipe Recipe) MarshalYAML() ([]byte, error) {
	if recipe.Steps == nil {
		recipe.Steps = make([]Step, 0)
	}
	return yamlv3.Marshal(recipe)
}

func (recipe *Recipe) UnmarshalYAML(bytes []byte) error {
	return yamlv3.Unmarshal(bytes, &recipe)
}

type Step struct {
	Action      string      `json:"action" yaml:"action"`
	Measurement Measurement `json:"measurement" yaml:"measurement"`
}

func (step Step) MarshalJSON() ([]byte, error) {
	return json.Marshal(step)
}

func (step *Step) UnmarshalJSON(bytes []byte) error {
	return json.Unmarshal(bytes, &step)
}

func (step Step) MarshalYAML() ([]byte, error) {
	return yamlv3.Marshal(step)
}

func (step *Step) UnmarshalYAML(bytes []byte) error {
	return yamlv3.Unmarshal(bytes, &step)
}
